server:
  port: 9000                         

jwt:
  secretKey: SushantGargiSecretKeyForJWTMustBe32Chars12

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - LoggingOrdersFilter            
            - name: Authentication            
              args:
                is-enabled: true
                allowed-roles: [USER, ADMIN]

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Sushant
            - name: Authentication           
              args:
                is-enabled: true
                allowed-roles: [ADMIN]

        - id: shipping-service             
          uri: lb://shipping-service
          predicates:
            - Path=/api/v1/shipping/**
          filters:
            - StripPrefix=2
            - name: Authentication
              args:
                is-enabled: true
                llowed-roles: [USER, ADMIN]
