server.servlet.context-path=/orders
server.port=9021

spring.datasource.url=jdbc:postgresql://order-db:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

my.variable=HelloFromConfigServer
features.user-tracking-enabled=true

resilience4j.retry.configs.default.maxRetryAttempts=3
resilience4j.retry.configs.default.waitDuration=100ms
resilience4j.retry.instances.inventoryRetry.baseConfig=default
resilience4j.retry.instances.inventoryRetry.waitDuration=200ms
resilience4j.retry.instances.shippingRetry.baseConfig=default
resilience4j.retry.instances.shippingRetry.maxRetryAttempts=3
resilience4j.retry.instances.shippingRetry.waitDuration=200ms

resilience4j.ratelimiter.instances.inventoryRateLimiter.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.inventoryRateLimiter.limitForPeriod=100
resilience4j.ratelimiter.instances.inventoryRateLimiter.timeoutDuration=10ms

resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.waitDurationInOpenState=1s
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.eventConsumerBufferSize=10

kafka.topic.order-created=order_created
kafka.topic.order-status-updated=order_status_updated

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=http://schema-registry:8081

spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=http://schema-registry:8081
spring.kafka.consumer.properties.specific.avro.reader=true
